### ISSUE TITLE
How to render the generated menu?

### ISSUE THREAD

**Issue by momostafa** [tomatophp/filament-menus#1]
Hi thanks for the awesome plugin very nice frontend  interface but I am stuck and don't know where and how to register the generate code <x-filament-menu menu="main-menu"/> 
please provide detailed instructions thanks

**Comment by 3x1io** [comment]
hi @momostafa you can use it anywhere as a custom component like this

```html

<x-filament-menu menu="dashboard"/> 

```

**Comment by momostafa** [comment]
Hi, 

After the last update finally i was able to figure out how to make your awesome plugin work :) thanks for providing it for free.

for anyone else the <x-filament-menu menu="dashboard"/>  should be placed inside /resources/views/layouts/app.blade.php  after {{ $slot }}
    <body class="antialiased">

        {{ $slot }}
        <x-filament-menu menu="main-menu"/>

as of version 1.0.3 inside filament service provider
/app/Providers/Filament/AdminPanelProvider.php
add  use TomatoPHP\FilamentMenus\Services\FilamentMenuLoader; (Please update the documentation) 

I made a small modification to display a select menu to move menu items from one menu to another 

/vendor/tomatophp/filament-menus/src/Resources/MenuResource/Relations/MenuItems.php

  
```php
return $form->schema([
            Forms\Components\Grid::make(["default" => 1])->schema(array_merge([
                Forms\Components\Select::make('menu_id')
                    ->label(trans('Select Menu Name'))
                    ->required()
                    ->relationship('menu', 'title'),
``` 

Awesome plugin thanks again

**Comment by 3x1io** [comment]
@momostafa nice idea to make a selection of menu i think it can fix a lot.

**Comment by momostafa** [comment]
> @momostafa nice idea to make a selection of menu i think it can fix a lot.

your plugin saved me a lot of time thanks again and very nice UI
